### ISSUE TITLE
ValueError: unknown format: models/Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin

### ISSUE THREAD

**Issue by LMX-xin** [ouwei2013/baichuan13b.cpp#6]
# Prerequisites
  #python3 convert.py models/Baichuan-13B-Chat/

Encountered the following error:

Traceback (most recent call last):
  File "/home/Baichuan13B/baichuan13b.cpp/convert.py", line 1263, in <module>
    main()
  File "/home/Baichuan13B/baichuan13b.cpp/convert.py", line 1243, in main
    model_plus = load_some_model(args.model)
  File "/home/Baichuan13B/baichuan13b.cpp/convert.py", line 1164, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/home/Baichuan13B/baichuan13b.cpp/convert.py", line 962, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: models/Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin

#This is the Baichuan13B I downloaded according to the readme：

root@2c88572cf70d:/home/Baichuan13B/baichuan13b.cpp/models/Baichuan-13B-Chat# ls
'Baichuan-13B '$'\346\250\241\345\236\213\347\244\276\345\214\272\350\256\270\345\217\257\345\215\217\350\256\256''.pdf'   pytorch_model-00002-of-00003.bin
'Community License for Baichuan-13B Model.pdf'                                                                             pytorch_model-00003-of-00003.bin
 README.md                                                                                                                 pytorch_model.bin.index.json
 config.json                                                                                                               quantizer.py
 configuration_baichuan.py                                                                                                 requirements.txt
 generation_config.json                                                                                                    special_tokens_map.json
 generation_utils.py                                                                                                       tokenization_baichuan.py
 handler.py                                                                                                                tokenizer.model
 modeling_baichuan.py                                                                                                      tokenizer_config.json
 pytorch_model-00001-of-00003.bin

   #The platform I use is Linux platform。Can you check the error for me?

**Comment by ouwei2013** [comment]
Can you please provide the command for converting the files? I think the error is about wrong dir path.

**Comment by LMX-xin** [comment]
Do you want to see this command?
the command for converting the files：

python3 /home/limenxin/Baichuan13B/baichuan13b.cpp/convert.py /home/limenxin/Baichuan13B/baichuan13b.cpp/models/Baichuan-13B-Chat/

I convert the model to ggml FP16 format according to Prepare Data & Run in the readme in your github repository
my convert.py in this path ：/home/limenxin/Baichuan13B/baichuan13b.cpp/
my Baichuan-13B-Chat  in this path:/home/limenxin/Baichuan13B/baichuan13b.cpp/models









At 2023-08-24 09:34:19, "OU Wei" ***@***.***> wrote:

Can you please provide the command for converting the files? I think the error is about wrong dir path.

**Comment by ouwei2013** [comment]
Can you check the sizes of your downloaded files : pytorch_model-00001-of-00003.bin, pytorch_model-00002-of-00003.bin, pytorch_model-00003-of-00003.bin. If downloaded properly, each of these files should be of 6-10 GB. I suspect the pytorch_model-00001-of-00003.bin file in your download is corrupt. 

You can verify this by running in python:

path='Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin' ########  (your baichuan model path) 
fp = open(path, 'rb')
first8 = fp.read(8)
fp.seek(0)
print(first8[:2])

If the code fails to print 'pk' then the binary file is corrupt. Please re-download them from huggingface.

**Comment by LMX-xin** [comment]
> Can you check the sizes of your downloaded files : pytorch_model-00001-of-00003.bin, pytorch_model-00002-of-00003.bin, pytorch_model-00003-of-00003.bin. If downloaded properly, each of these files should be of 6-10 GB. I suspect the pytorch_model-00001-of-00003.bin file in your download is corrupt.
> 
> You can verify this by running in python:
> 
> path='Baichuan-13B-Chat/pytorch_model-00001-of-00003.bin' ######## (your baichuan model path) fp = open(path, 'rb') first8 = fp.read(8) fp.seek(0) print(first8[:2])
> 
> If the code fails to print 'pk' then the binary file is corrupt. Please re-download them from huggingface.

Thanks,The program is already running
